#-------------------------------------------------------------------------------------
# PREREQUISITE 
# CHANGE NAMESPACE AND NAME OF ROLE
#-------------------------------------------------------------------------------------  

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-role
  namespace: dev
rules:
- apiGroups: [ "" ]
  resources: [ "secrets" ]
  verbs: [ "get", "list", "create", "update", "delete" ]
